repository_type: pipeline

lint:
    files_unchanged:
        - lib/NfcoreTemplate.groovy
        - .github/workflows/branch.yml
        - .github/workflows/linting_comment.yml
        - .github/workflows/linting.yml
