name: nf-core-mag-1.0.0
channels:
  - bioconda
  - conda-forge
  - defaults
  - ursky
dependencies:
  - fastqc=0.11.8
  - multiqc=1.6
  - fastp=0.19.5
  - megahit=1.1.3
  - metabat2=2.12.1
  - samtools=1.9
  - bowtie2=2.3.4.3
  - quast=5.0.2
  - hmmer=3.2.1
  - prodigal=2.6.3
  - pplacer=1.1.alpha19
  - diamond=0.9.22
  - python=2.7.15
  - r=3.5.1
  - biopython=1.72
  - krona=2.7
  - conda-forge::r-markdown=0.8
