name: nf-core Docker push
# This builds the docker image and pushes it to DockerHub
# Runs on nf-core repo releases and push event to 'dev' branch (PR merges)
on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  push_dockerhub:
    name: Push new Docker image to Docker Hub
    runs-on: ubuntu-latest
    # Only run for the nf-core repo, for releases and merged PRs
    if: ${{ github.repository == 'nf-core/mag' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Build new docker image
        run: docker build --no-cache . -t nfcore/mag:latest

      - name: Push Docker image to DockerHub (dev)
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker tag nfcore/mag:latest nfcore/mag:dev
          docker push nfcore/mag:dev

      - name: Push Docker image to DockerHub (release)
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push nfcore/mag:latest
          docker tag nfcore/mag:latest nfcore/mag:${{ github.event.release.tag_name }}
          docker push nfcore/mag:${{ github.event.release.tag_name }}

      - name: Build new docker image for BUSCO
        run: docker build --no-cache ./containers/busco/ -t nfcore/magbusco:latest

      - name: Push Docker image for BUSCO to DockerHub (dev)
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker tag nfcore/magbusco:latest nfcore/magbusco:dev
          docker push nfcore/magbusco:dev

      - name: Push Docker image for BUSCO to DockerHub (release)
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push nfcore/magbusco:latest
          docker tag nfcore/magbusco:latest nfcore/magbusco:${{ github.event.release.tag_name }}
          docker push nfcore/magbusco:${{ github.event.release.tag_name }}
